modLoader = "javafml"
loaderVersion = "[43,)"
license = "Terrarium Licence"
issueTrackerURL = "https://github.com/terrarium-earth/modid/issues"

[[mods]]
modId = "lookinsharp"
version = "${version}"
displayName = "Lookin' Sharp!"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/lookin-sharp"
logoFile = "icon.png"
authors = ""
credits = ""
description = ""

[[dependencies.lookinsharp]]
modId = "forge"
mandatory = true
versionRange = "[47.1.0,47.1.3]"
ordering = "NONE"
side = "BOTH"

[[dependencies.lookinsharp]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lookinsharp]]
modId = "resourcefullib"
mandatory = true
versionRange = "[${resourcefullib_version},)"
ordering = "NONE"
side = "BOTH"
